### PR TITLE
Use jupyterlab-lsp for linting

### PR DESCRIPTION
**Pull request by sverhoeven**
Should be merged after #55

### CODE REVIEW

**Comment by sverhoeven** [comment]
Uses default lint rules now. 

This lab extension (https://github.com/krassowski/jupyterlab-lsp) also changes auto complete behavior which might not be wanted.

**Comment by SarahAlidoost** [comment]
with this extension, auto-complete and tool-tips appear very slow.

**Comment by sverhoeven** [comment]
Closing for a better solution

**Comment by SarahAlidoost** [comment]
As discussed, We add this extension for now and consider its improvements in the future. So, this PR is reopened.

**Comment by SarahAlidoost** [comment]
This PR is blocked by issue #66.

**Comment by sverhoeven** [comment]
Outdated

**Pull request closed without merging**
