### PR TITLE
Repair provision

### PR DESCRIPTION
**Pull request by sverhoeven**
On local vagrant machine the provisioning failed. This PR makes it go OK again.

Required fix for terria at https://github.com/eWaterCycle/terriajs/commit/41036cf9c10cf8c4dc1734e361b9f8395f8ab2ed

### CODE REVIEW

**Comment by sverhoeven** [comment]
Test by me on vagrant and surf research cloud.
1. [x] login to jupyter hub
2. [x] login with ssh
3. [x] dcache mounted
4. [x] Run ewatercycle/docs/examples/MarrmotM01.ipynb , tests dcache and singularity
5. [x] nbgitpuller by clicking `Example notebooks` on homepage.

There is a `ERROR 1: PROJ: proj_create_from_database: Open of /opt/conda/envs/ewatercycle/share/proj failed` error on `import ewatercycle.forcing`

**Comment by sverhoeven** [comment]
PROJ error has been fixed and can become root.

**Review by Peter9192 — APPROVED** [review]
Tested by
- becoming root
- start and run experiment from launcher
- login to jupyter
- run example notebook for wflow and forcing
- run techpaper notebook for marrmot

**Comment by sverhoeven** [comment]
Great, thanks for testing.

**Comment by sverhoeven** [comment]
Also tested creating experiment notebook from terria catchment selection.

**Pull request merged**
