### PR TITLE
Replace rclone mount of dcache with a Samba mount

### PR DESCRIPTION
**Pull request by sverhoeven**
See https://github.com/eWaterCycle/infra/issues/159#issuecomment-2047258343

### CODE REVIEW

**Comment by sverhoeven** [comment]
Running playbook on SRC file server with tmux.

**Comment by sverhoeven** [comment]
Got

```
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["/opt/conda//bin/python", "/tmp/era5process.py", "1990", "mean_sea_level_pressure", "psl", "/data/volume_2/samba-share/climate-data/obs6/Tier3/ERA5/OBS6_ERA5_reanaly_1_day_psl_1990-1990.nc"], "delta": "0:00:05.541362", "end": "2024-05-17 07:47:59.721476", "msg": "non-zero return code", "rc": 1, "start": "2024-05-17 07:47:54.180114", "stderr": "ERROR 1: PROJ: proj_create_from_database: Open of /opt/conda/share/proj failed
Traceback (most recent call last):
  File \"/tmp/era5process.py\", line 46, in <module>
    orig_file = eds.files[0]
                ~~~~~~~~~^^^
IndexError: list index out of range", "stderr_lines": ["ERROR 1: PROJ: proj_create_from_database: Open of /opt/conda/share/proj failed", "Traceback (most recent call last):", "  File \"/tmp/era5process.py\", line 46, in <module>", "    orig_file = eds.files[0]", "                ~~~~~~~~~^^^", "IndexError: list index out of range"], "stdout": "Processing ERA5 mean_sea_level_pressure data from year 1990 to psl and saving to /data/volume_2/samba-share/climate-data/obs6/Tier3/ERA5/OBS6_ERA5_reanaly_1_day_psl_1990-1990.nc", "stdout_lines": ["Processing ERA5 mean_sea_level_pressure data from year 1990 to psl and saving to /data/volume_2/samba-share/climate-data/obs6/Tier3/ERA5/OBS6_ERA5_reanaly_1_day_psl_1990-1990.nc"]}

```

It was looking for input files in 1hrPt instead of 1hr.
We need to make scripts mip aware. For now resumed download of raw era5 data, skippiing cmorization.

**Comment by sverhoeven** [comment]
Tthe climate data download completed, now stuck on 

<details>
<summary>grdc download</summary>

```
TASK [grdc : GTN-R - monthlies] ************************************************************************************************************************************************************Thursday 06 June 2024  11:47:58 +0200 (0:00:00.520)       0:15:47.553 *********                                                                                                             failed: [localhost] (item={'range': '1931-1960', 'url': 'https://gemstat.bafg.de/KiWISGRDC/KiWIS?datasource=1&service=SOS&version=2.0&request=GetObservation&featureOfInterest=http://gemstat.bafg.de/stations/1104150,1104530,1159100,1160235,1160378,1160500,1160580,1160684,1160788,1160880,1255100,1257100,1259100,1445100,1732100,1733600&temporalFilter=phenomenonTime,1931-01-01T00:00:00.000Z/1960-12-31T00:00:00.000Z'}) => {"ansible_loop_var": "period", "changed": false, "dest": "/data/volume_2/samba-share/observation/grdc/monthlies/GTNR_1.1931-1960.wml2", "elapsed": 0, "msg": "Request failed", "period": {"range": "1931-1960", "url": "https://gemstat.bafg.de/KiWISGRDC/KiWIS?datasource=1&service=SOS&version=2.0&request=GetObservation&featureOfInterest=http://gemstat.bafg.de/stations/1104150,1104530,1159100,1160235,1160378,1160500,1160580,1160684,1160788,1160880,1255100,1257100,1259100,1445100,1732100,1733600&temporalFilter=phenomenonTime,1931-01-01T00:00:00.000Z/1960-12-31T00:00:00.000Z"}, "response": "HTTP Error 404: Not Found", "status_code": 404, "url": "https://gemstat.bafg.de/KiWISGRDC/KiWIS?datasource=1&service=SOS&version=2.0&request=GetObservation&featureOfInterest=http://gemstat.bafg.de/stations/1104150,1104530,1159100,1160235,1160378,1160500,1160580,1160684,1160788,1160880,1255100,1257100,1259100,1445100,1732100,1733600&temporalFilter=phenomenonTime,1931-01-01T00:00:00.000Z/1960-12-31T00:00:00.000Z"}  
```

</details>

**Comment by BSchilperoort** [comment]
> Tthe climate data download completed, now stuck on
> grdc download

Seems like the GRDC uses a different portal now. I'm not sure if we can still download data from there :/

**Comment by sverhoeven** [comment]
Merged into https://github.com/eWaterCycle/infra/pull/169

**Pull request closed without merging**
