### PR TITLE
Added ERA5 and ERA-Interim calibrated parameter sets for wflow

### PR DESCRIPTION
**Pull request by sverhoeven**
Result of wflow parameter set reshuffling at https://github.com/eWaterCycle/infra/issues/94#issuecomment-915256255

### CODE REVIEW

**Review by Peter9192 — COMMENTED** [review]
Tried generating and running Rhine_ERA5-calibrated. Hitting a lot of timeouts on my local VM on model.setup, but eventually got through. Then got 

```
_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: 'pcraster._pcraster.Field' object is not iterable"
	debug_error_string = "{"created":"@1631181243.281355688","description":"Error received from peer ipv4:127.0.0.1:42727","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Exception calling application: 'pcraster._pcraster.Field' object is not iterable","grpc_status":2}"
>
```

<details><summar>wflow.log</summary>

```
2021-09-09 09:53:53,841 - wflow_ewatercycle.ini - pcrut - DEBUG - File logging to /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/run_default/wflow.log
2021-09-09 09:53:53,841 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - wflow_ewatercycle.ini 2020.1.2.dev8+gfdb404c5 Case: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233 Runid: run_default
2021-09-09 09:53:53,841 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Initialise framework version: 2020.1.2.dev8+gfdb404c5
2021-09-09 09:53:53,842 - wflow_ewatercycle.ini - wf_DynamicFramework - WARNING - Ini file made for wflow_sbm but found wflow.wflow_sbm in code.
2021-09-09 09:53:53,843 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Found following input variables to get from netcdf file: ['pr', 'pet', 'tas', 'IF', 'pr', 'tas', 'pet', 'IF']
2021-09-09 09:53:54,140 - wflow_ewatercycle.ini - wf_netcdfio - INFO - Reading input from netCDF file: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/wflow_ERA5_Rhine_2002_2002.nc
2021-09-09 09:53:54,182 - wflow_ewatercycle.ini - wf_netcdfio - WARNING - Variable IF not found in netcdf file: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/wflow_ERA5_Rhine_2002_2002.nc
2021-09-09 09:53:54,182 - wflow_ewatercycle.ini - wf_netcdfio - WARNING - Variable IF not found in netcdf file: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/wflow_ERA5_Rhine_2002_2002.nc
2021-09-09 09:53:54,204 - wflow_ewatercycle.ini - wf_netcdfio - INFO - Setting up netcdf output: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/run_default/outmaps.nc
2021-09-09 09:53:54,205 - wflow_ewatercycle.ini - wf_netcdfio - INFO - Setting up dimensions and attributes. Steps: 365 lat: 678 lon: 774
2021-09-09 09:53:54,853 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Creating parameter specification for par: Sl (['staticmaps/Sl.map', 'staticmap', '0.1', '1'])
2021-09-09 09:53:54,853 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Creating parameter specification for par: Kext (['staticmaps/Kext.map', 'staticmap', '0.6', '1'])
2021-09-09 09:53:54,853 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Creating parameter specification for par: Swood (['staticmaps/Swood.map', 'staticmap', '0.5', '1'])
2021-09-09 09:53:54,853 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Creating parameter specification for par: LAI (['staticmaps/clim/LAI', 'monthlyclim', '1.0', '1'])
2021-09-09 09:53:54,853 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Creating parameter specification for par: LakeLocs (['staticmaps/wflow_lakelocs.map', 'staticmap', '0.0', '0'])
2021-09-09 09:53:54,853 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Creating parameter specification for par: LakeAreasMap (['staticmaps/wflow_lakeareas.map', 'staticmap', '0.0', '0'])
2021-09-09 09:53:54,854 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Creating parameter specification for par: LinkedLakeLocs (['intbl/LinkedLakeLocs.tbl', 'tbl', '0', '0', 'staticmaps/wflow_lakelocs.map'])
2021-09-09 09:53:54,854 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Creating parameter specification for par: LakeStorFunc (['intbl/LakeStorFunc.tbl', 'tbl', '1', '0', 'staticmaps/wflow_lakelocs.map'])
2021-09-09 09:53:54,854 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Creating parameter specification for par: LakeOutflowFunc (['intbl/LakeOutflowFunc.tbl', 'tbl', '3', '0', 'staticmaps/wflow_lakelocs.map'])
2021-09-09 09:53:54,854 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Creating parameter specification for par: LakeArea (['intbl/LakeArea.tbl', 'tbl', '1', '0', 'staticmaps/wflow_lakelocs.map'])
2021-09-09 09:53:54,854 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Creating parameter specification for par: LakeAvgLevel (['intbl/LakeAvgLevel.tbl', 'tbl', '1', '0', 'staticmaps/wflow_lakelocs.map'])
2021-09-09 09:53:54,854 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Creating parameter specification for par: LakeAvgOut (['intbl/LakeAvgOut.tbl', 'tbl', '1', '0', 'staticmaps/wflow_lakelocs.map'])
2021-09-09 09:53:54,854 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Creating parameter specification for par: LakeThreshold (['intbl/LakeThreshold.tbl', 'tbl', '0', '0', 'staticmaps/wflow_lakelocs.map'])
2021-09-09 09:53:54,854 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Creating parameter specification for par: Lake_b (['intbl/Lake_b.tbl', 'tbl', '50', '0', 'staticmaps/wflow_lakelocs.map'])
2021-09-09 09:53:54,854 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Creating parameter specification for par: Lake_e (['intbl/Lake_e.tbl', 'tbl', '2.0', '0', 'staticmaps/wflow_lakelocs.map'])
2021-09-09 09:53:54,877 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Adding csv output at /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/staticmaps/grdc_station.map function: average
2021-09-09 09:53:54,878 - wflow_ewatercycle.ini - wflow_sbm - INFO - running for 365 timesteps
2021-09-09 09:53:54,879 - wflow_ewatercycle.ini - wflow_sbm - INFO - Using sub timestep for kinematic wave (iterate)
2021-09-09 09:53:54,879 - wflow_ewatercycle.ini - wflow_sbm - INFO - Using a fixed timestep (seconds) for kinematic wave river flow: 900
2021-09-09 09:53:54,981 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Static input data (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/staticmaps/wflow_riverlength_fact.map)  not present, returning 1.0
2021-09-09 09:53:55,091 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Static input data (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/staticmaps/wflow_inflow.map)  not present, returning 0.0
2021-09-09 09:53:55,125 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Static input data (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233\staticmaps/wflow_tempcor.map)  not present, returning 0.0
2021-09-09 09:53:55,155 - wflow_ewatercycle.ini - wflow_sbm - INFO - Linking parameters to landuse, catchment and soil...
2021-09-09 09:53:55,155 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Adding Precipitation to model.
2021-09-09 09:53:55,155 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Static input data (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/pr.map)  not present, returning 0.0
2021-09-09 09:53:55,161 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Adding PotenEvap to model.
2021-09-09 09:53:55,162 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Static input data (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/pet.map)  not present, returning 0.0
2021-09-09 09:53:55,168 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Adding Temperature to model.
2021-09-09 09:53:55,168 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Static input data (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/tas.map)  not present, returning 10.0
2021-09-09 09:53:55,173 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Adding Inflow to model.
2021-09-09 09:53:55,179 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Adding IrrigationAreas to model.
2021-09-09 09:53:55,180 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Static input data (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/staticmaps/wflow_irrigationareas.map)  not present, returning 0.0
2021-09-09 09:53:55,182 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Adding IrrigationSurfaceIntakes to model.
2021-09-09 09:53:55,182 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Static input data (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/staticmaps/wflow_irrisurfaceintake.map)  not present, returning 0.0
2021-09-09 09:53:55,185 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Adding IrrigationPaddyAreas to model.
2021-09-09 09:53:55,185 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Static input data (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/staticmaps/wflow_irrigationpaddyareas.map)  not present, returning 0.0
2021-09-09 09:53:55,189 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Adding IrrigationSurfaceReturn to model.
2021-09-09 09:53:55,190 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Static input data (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/staticmaps/wflow_irrisurfacereturns.map)  not present, returning 0.0
2021-09-09 09:53:55,192 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Adding h_max to model.
2021-09-09 09:53:55,192 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Static input data (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/staticmaps/wflow_hmax.map)  not present, returning 0.0
2021-09-09 09:53:55,194 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Adding h_min to model.
2021-09-09 09:53:55,195 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Static input data (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/staticmaps/wflow_hmin.map)  not present, returning 0.0
2021-09-09 09:53:55,197 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Adding h_p to model.
2021-09-09 09:53:55,197 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - Static input data (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/staticmaps/wflow_hp.map)  not present, returning 0.0
2021-09-09 09:53:55,199 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Adding Sl to model.
2021-09-09 09:53:55,274 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Adding Kext to model.
2021-09-09 09:53:55,312 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Adding Swood to model.
2021-09-09 09:53:55,340 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Adding LAI to model.
2021-09-09 09:53:55,407 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Adding LakeLocs to model.
2021-09-09 09:53:55,449 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Adding LakeAreasMap to model.
2021-09-09 09:53:55,487 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Initial: Adding LinkedLakeLocs to model.
2021-09-09 09:53:55,488 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - tbl file not found (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/LinkedLakeLocs.tbl) returning default value: 0.0
2021-09-09 09:53:55,489 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Initial: Adding LakeStorFunc to model.
2021-09-09 09:53:55,489 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - tbl file not found (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/LakeStorFunc.tbl) returning default value: 1.0
2021-09-09 09:53:55,490 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Initial: Adding LakeOutflowFunc to model.
2021-09-09 09:53:55,490 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - tbl file not found (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/LakeOutflowFunc.tbl) returning default value: 3.0
2021-09-09 09:53:55,491 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Initial: Adding LakeArea to model.
2021-09-09 09:53:55,510 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Initial: Adding LakeAvgLevel to model.
2021-09-09 09:53:55,524 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Initial: Adding LakeAvgOut to model.
2021-09-09 09:53:55,537 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Initial: Adding LakeThreshold to model.
2021-09-09 09:53:55,538 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - tbl file not found (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/LakeThreshold.tbl) returning default value: 0.0
2021-09-09 09:53:55,539 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Initial: Adding Lake_b to model.
2021-09-09 09:53:55,553 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Initial: Adding Lake_e to model.
2021-09-09 09:53:55,553 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - tbl file not found (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/Lake_e.tbl) returning default value: 2.0
2021-09-09 09:53:55,574 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - reading map parameter file: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/../staticmaps/RootingDepth.map
2021-09-09 09:53:55,619 - wflow_ewatercycle.ini - wf_DynamicFramework - WARNING - tbl file not found (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/AirEntryPressure.tbl) returning default value: 10.0
2021-09-09 09:53:55,668 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Creating map from table: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/rootdistpar.tbl
2021-09-09 09:53:55,717 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Creating map from table: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/InfiltCapSoil.tbl
2021-09-09 09:53:55,744 - wflow_ewatercycle.ini - wf_DynamicFramework - WARNING - tbl file not found (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/CapScale.tbl) returning default value: 100.0
2021-09-09 09:53:55,817 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Creating map from table: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/InfiltCapPath.tbl
2021-09-09 09:53:55,879 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Creating map from table: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/MaxLeakage.tbl
2021-09-09 09:53:55,904 - wflow_ewatercycle.ini - wf_DynamicFramework - WARNING - tbl file not found (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/MaxPercolation.tbl) returning default value: 0.0
2021-09-09 09:53:55,932 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - reading map parameter file: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/../staticmaps/PathFrac.map
2021-09-09 09:53:55,981 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - reading map parameter file: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/../staticmaps/SoilThickness.map
2021-09-09 09:53:56,021 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - reading map parameter file: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/../staticmaps/thetaR.map
2021-09-09 09:53:56,052 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - reading map parameter file: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/../staticmaps/thetaS.map
2021-09-09 09:53:56,092 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - reading map parameter file: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/../staticmaps/SoilMinThickness.map
2021-09-09 09:53:56,134 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - reading map parameter file: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/../staticmaps/KsatVer.map
2021-09-09 09:53:56,193 - wflow_ewatercycle.ini - wf_DynamicFramework - WARNING - tbl file not found (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/MporeFrac.tbl) returning default value: 0.0
2021-09-09 09:53:56,253 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Creating map from table: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/KsatHorFrac.tbl
2021-09-09 09:53:56,285 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - reading map parameter file: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/../staticmaps/M.map
2021-09-09 09:53:56,330 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - reading map parameter file: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/../staticmaps/N.map
2021-09-09 09:53:56,450 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - reading map parameter file: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/../staticmaps/WaterFrac.map
2021-09-09 09:53:56,482 - wflow_ewatercycle.ini - wf_DynamicFramework - WARNING - tbl file not found (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/et_reftopot.tbl) returning default value: 1.0
2021-09-09 09:53:56,561 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Creating map from table: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/TTI.tbl
2021-09-09 09:53:56,626 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Creating map from table: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/TT.tbl
2021-09-09 09:53:56,701 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Creating map from table: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/TTM.tbl
2021-09-09 09:53:56,763 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Creating map from table: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/Cfmax.tbl
2021-09-09 09:53:56,828 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - Creating map from table: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/WHC.tbl
2021-09-09 09:53:56,855 - wflow_ewatercycle.ini - wf_DynamicFramework - WARNING - tbl file not found (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/w_soil.tbl) returning default value: 0.1125
2021-09-09 09:53:57,195 - wflow_ewatercycle.ini - wflow_sbm - INFO - A total of 0 simple reservoirs and 10 lakes found.
2021-09-09 09:53:57,578 - wflow_ewatercycle.ini - wf_DynamicFramework - WARNING - tbl file not found (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/KsatVerFrac.tbl) returning default value: 1.0
2021-09-09 09:53:57,598 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - reading map parameter file: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/../staticmaps/c_0.map
2021-09-09 09:53:57,688 - wflow_ewatercycle.ini - wf_DynamicFramework - WARNING - tbl file not found (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/KsatVerFrac.tbl) returning default value: 1.0
2021-09-09 09:53:57,736 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - reading map parameter file: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/../staticmaps/c_1.map
2021-09-09 09:53:57,767 - wflow_ewatercycle.ini - wf_DynamicFramework - WARNING - tbl file not found (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/KsatVerFrac.tbl) returning default value: 1.0
2021-09-09 09:53:57,794 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - reading map parameter file: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/../staticmaps/c_2.map
2021-09-09 09:53:57,891 - wflow_ewatercycle.ini - wf_DynamicFramework - WARNING - tbl file not found (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/KsatVerFrac.tbl) returning default value: 1.0
2021-09-09 09:53:57,937 - wflow_ewatercycle.ini - wf_DynamicFramework - INFO - reading map parameter file: /home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/intbl/../staticmaps/c_3.map
2021-09-09 09:53:57,995 - wflow_ewatercycle.ini - wflow_sbm - INFO - Initializing of model variables..
2021-09-09 09:54:03,140 - wflow_ewatercycle.ini - wflow_sbm - INFO - Saving summary maps...
2021-09-09 09:54:03,141 - wflow_ewatercycle.ini - wflow_sbm - INFO - End of initial section
2021-09-09 09:54:03,143 - wflow_ewatercycle.ini - wflow_sbm - INFO - Setting initial conditions from state files
2021-09-09 09:54:03,144 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - State input data (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/instate/RiverRunoff.map)  not present, returning 0.0
2021-09-09 09:54:03,144 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - State input data (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/instate/WaterLevelR.map)  not present, returning 0.0
2021-09-09 09:54:03,144 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - State input data (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/instate/LandRunoff.map)  not present, returning 0.0
2021-09-09 09:54:03,144 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - State input data (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/instate/WaterLevelL.map)  not present, returning 0.0
2021-09-09 09:54:03,145 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - State input data (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/instate/SatWaterDepth.map)  not present, returning 0.0
2021-09-09 09:54:03,145 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - State input data (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/instate/Snow.map)  not present, returning 0.0
2021-09-09 09:54:03,145 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - State input data (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/instate/TSoil.map)  not present, returning 0.0
2021-09-09 09:54:03,145 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - State input data (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/instate/UStoreLayerDepth.map)  not present, returning 0.0
2021-09-09 09:54:03,145 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - State input data (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/instate/SnowWater.map)  not present, returning 0.0
2021-09-09 09:54:03,145 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - State input data (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/instate/CanopyStorage.map)  not present, returning 0.0
2021-09-09 09:54:03,146 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - State input data (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/instate/SubsurfaceFlow.map)  not present, returning 0.0
2021-09-09 09:54:03,146 - wflow_ewatercycle.ini - wf_DynamicFramework - DEBUG - State input data (/home/vagrant/f240d42c-3bed-47d2-bf0f-74683618ea8f/ewatercycle_output/wflow_20210909_095233/instate/LakeWaterLevel.map)  not present, returning 0.0

```

</details>

**Comment by Peter9192** [comment]
Getting the same error for Merrimack

**Comment by sverhoeven** [comment]
Doh, the zip file had empty instate dir, into which i moved instate_era5. Reuploading pararmeter sets.

**Comment by sverhoeven** [comment]
On closer inspection doring is missing era-interim instate and savannah is missing era5 instate. Will remove those from dcache and config file

**Comment by sverhoeven** [comment]
instate/ dirs now have files in them. tested on vagrant with `wflow / Merrimack / 2002-01-01 - 2002-12-31 / ERA5`

**Review by Peter9192 — APPROVED** [review]
Merrimack also works on my VM now. Rhine fails with timeout. However, that's not related to this PR.

**Comment by sverhoeven** [comment]
Thanks for reviewing. 

Found typo while testing https://github.com/eWaterCycle/infra/issues/91, so also fixed it this PR.

**Pull request merged**
