### PR TITLE
Single conda Jupyter kernel

### LINKED ISSUE #47: Single Conda Jupyter kernel
The packages available in OS python and conda are different. Some packages can only be easily installed in conda like ESMValtool. Picking a kernel for a notebook can be confusing.

### PR DESCRIPTION
**Pull request by Peter9192**
closes #47

- [x] Remove python kernel from kernelspec
- [x] Turn off native kernel in spawned notebooks
- [x] Update notebook dependencies/lab extension setup to use conda python instead of system python
- [x] Add conda init to user shell
- [x] Maybe rename default notebook? Currently: Python3 (Conda)

### CODE REVIEW

**Comment by Peter9192** [comment]
Status update: 

Main jupyterhub/lab environment switched over to ewatercycle conda environment. Need to 

- [ ] Add packages from the era5-comparison environment
- [ ] Add packages from pangeo
- [ ] Try to add pymt/esmvaltool/hymuse/grpc4bmi to the default ewatercycle env rather than their own or the base env.
- [ ] Clean up the playbook, roles and tasks
- [ ] Verify that everything still works

**Comment by Peter9192** [comment]
@sverhoeven this is as far as I got before my holidays. Unfortunately I didn't have time to do a clean installation of the VM and then test whether the upgrade works with this playbook. My current testing VM might be a bit polluted.

- I think there might still be remnants of old kernels when you do an upgrade from the current environment. I left some commented lines that might be helpful to remove them. 
- I didn't remove the sample notebooks, but that seems a reasonable thing to do (maybe in another PR?)
- The grpc4bmi task in jupyter role can also be cleaned further. Since the installation of grpc4bmi itself has moved to ewatercycle role, it's just a collection of docker pulls and singularity builds. More like a 'data' task than 'grpc4bmi'.
- I now run conda init for all users, but ideally the ewatercycle environment should also be activated on login.

**Comment by sverhoeven** [comment]
Also installed hymuse in conda, but running https://github.com/eWaterCycle/HyMUSE/blob/master/examples/heat/heat_example.py   cause 2 python process using 100% cpu and no progress so had to cancel it.

**Comment by sverhoeven** [comment]
This PR also fixes #50

Final steps before marking ready for review

1. [x] Create vagrant box provisioned from master branch
1. [x] Run ansible with this branch
1. [ ] Verify ewatercycle conda env is only kernel
1. [ ] Verify ewatercycle conda env is active in Jupyter terminal and after ssh login
1. [ ] run https://github.com/eWaterCycle/notebooks/blob/master/bmi/Walrus.ipynb
1  [ ] run geoviews example notebook
1. [ ] test code formatter extension
1. [ ] run pymt example notebook
1. [ ] test dask extension
1. [ ] Test `esmvaltool --help`

**Comment by sverhoeven** [comment]
For any reviewer I would suggest to use the same steps at https://github.com/eWaterCycle/infra/pull/55#issuecomment-659312725 to test if everything works.

**Comment by sverhoeven** [comment]
During provisioning a vagrant machine from nothing to this branch I noticed some issues. These could also popup during review or deployment to production. I am fixing them as I go through the provisioning from scratch.

**Comment by nielsdrost** [comment]
As a next step, I build the system on the master branch (with the exception of the culler), switched to the "47" branch, and ran ansible. It seems to be unhappy:

```
TASK [jupyter : grpc4bmi Docker images] ****************************************************************
failed: [vagrant.localhost] (item={'docker': 'ewatercycle/walrus-grpc4bmi', 'singularity': 'ewatercycle-walrus-grpc4bmi.sif'}) => {"ansible_loop_var": "item", "changed": false, "item": {"docker": "ewatercycle/walrus-grpc4bmi", "singularity": "ewatercycle-walrus-grpc4bmi.sif"}, "msg": "Cannot have both the docker-py and docker python modules (old and new version of Docker SDK for Python) installed together as they use the same namespace and cause a corrupt installation. Please uninstall both packages, and re-install only the docker-py or docker python module (for vagrant.localhost's Python /usr/bin/python3). It is recommended to install the docker module if no support for Python 2.6 is required. Please note that simply uninstalling one of the modules can leave the other module in a broken state."}
failed: [vagrant.localhost] (item={'docker': 'ewatercycle/pcrg-grpc4bmi', 'singularity': 'ewatercycle-pcrg-grpc4bmi.sif'}) => {"ansible_loop_var": "item", "changed": false, "item": {"docker": "ewatercycle/pcrg-grpc4bmi", "singularity": "ewatercycle-pcrg-grpc4bmi.sif"}, "msg": "Cannot have both the docker-py and docker python modules (old and new version of Docker SDK for Python) installed together as they use the same namespace and cause a corrupt installation. Please uninstall both packages, and re-install only the docker-py or docker python module (for vagrant.localhost's Python /usr/bin/python3). It is recommended to install the docker module if no support for Python 2.6 is required. Please note that simply uninstalling one of the modules can leave the other module in a broken state."}
failed: [vagrant.localhost] (item={'docker': 'ewatercycle/wflow-grpc4bmi', 'singularity': 'ewatercycle-wflow-grpc4bmi.sif'}) => {"ansible_loop_var": "item", "changed": false, "item": {"docker": "ewatercycle/wflow-grpc4bmi", "singularity": "ewatercycle-wflow-grpc4bmi.sif"}, "msg": "Cannot have both the docker-py and docker python modules (old and new version of Docker SDK for Python) installed together as they use the same namespace and cause a corrupt installation. Please uninstall both packages, and re-install only the docker-py or docker python module (for vagrant.localhost's Python /usr/bin/python3). It is recommended to install the docker module if no support for Python 2.6 is required. Please note that simply uninstalling one of the modules can leave the other module in a broken state."}
failed: [vagrant.localhost] (item={'docker': 'sverhoeven/marrmot', 'singularity': 'marrmot.sif'}) => {"ansible_loop_var": "item", "changed": false, "item": {"docker": "sverhoeven/marrmot", "singularity": "marrmot.sif"}, "msg": "Cannot have both the docker-py and docker python modules (old and new version of Docker SDK for Python) installed together as they use the same namespace and cause a corrupt installation. Please uninstall both packages, and re-install only the docker-py or docker python module (for vagrant.localhost's Python /usr/bin/python3). It is recommended to install the docker module if no support for Python 2.6 is required. Please note that simply uninstalling one of the modules can leave the other module in a broken state."}
failed: [vagrant.localhost] (item={'docker': 'ewatercycle/hype-grpc4bmi', 'singularity': 'ewatercycle-hype-grpc4bmi.sif'}) => {"ansible_loop_var": "item", "changed": false, "item": {"docker": "ewatercycle/hype-grpc4bmi", "singularity": "ewatercycle-hype-grpc4bmi.sif"}, "msg": "Cannot have both the docker-py and docker python modules (old and new version of Docker SDK for Python) installed together as they use the same namespace and cause a corrupt installation. Please uninstall both packages, and re-install only the docker-py or docker python module (for vagrant.localhost's Python /usr/bin/python3). It is recommended to install the docker module if no support for Python 2.6 is required. Please note that simply uninstalling one of the modules can leave the other module in a broken state."}
```

Should I manually un-install it?

**Comment by sverhoeven** [comment]
The previous task should have installed it, but it was in wrong Python and old package, corrected it in commits. 
Could you try again?

**Comment by nielsdrost** [comment]
> The previous task should have installed it, but it was in wrong Python and old package, corrected it in commits.
> Could you try again?

I tried again, still the same error...

```
TASK [jupyter : Docker Python package] *****************************************************************
ok: [vagrant.localhost]

TASK [jupyter : Remove old Docker-py python2 package] **************************************************
ok: [vagrant.localhost]

TASK [jupyter : Remove old Docker-py python3 package] **************************************************
ok: [vagrant.localhost]

TASK [jupyter : grpc4bmi Docker images] ****************************************************************
failed: [vagrant.localhost] (item={'docker': 'ewatercycle/walrus-grpc4bmi', 'singularity': 'ewatercycle-walrus-grpc4bmi.sif'}) => {"ansible_loop_var": "item", "changed": false, "item": {"docker": "ewatercycle/walrus-grpc4bmi", "singularity": "ewatercycle-walrus-grpc4bmi.sif"}, "msg": "Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on vagrant.localhost's Python /usr/bin/python3. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: cannot import name '__version__'"}
failed: [vagrant.localhost] (item={'docker': 'ewatercycle/pcrg-grpc4bmi', 'singularity': 'ewatercycle-pcrg-grpc4bmi.sif'}) => {"ansible_loop_var": "item", "changed": false, "item": {"docker": "ewatercycle/pcrg-grpc4bmi", "singularity": "ewatercycle-pcrg-grpc4bmi.sif"}, "msg": "Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on vagrant.localhost's Python /usr/bin/python3. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: cannot import name '__version__'"}
failed: [vagrant.localhost] (item={'docker': 'ewatercycle/wflow-grpc4bmi', 'singularity': 'ewatercycle-wflow-grpc4bmi.sif'}) => {"ansible_loop_var": "item", "changed": false, "item": {"docker": "ewatercycle/wflow-grpc4bmi", "singularity": "ewatercycle-wflow-grpc4bmi.sif"}, "msg": "Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on vagrant.localhost's Python /usr/bin/python3. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: cannot import name '__version__'"}
failed: [vagrant.localhost] (item={'docker': 'sverhoeven/marrmot', 'singularity': 'marrmot.sif'}) => {"ansible_loop_var": "item", "changed": false, "item": {"docker": "sverhoeven/marrmot", "singularity": "marrmot.sif"}, "msg": "Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on vagrant.localhost's Python /usr/bin/python3. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: cannot import name '__version__'"}
failed: [vagrant.localhost] (item={'docker': 'ewatercycle/hype-grpc4bmi', 'singularity': 'ewatercycle-hype-grpc4bmi.sif'}) => {"ansible_loop_var": "item", "changed": false, "item": {"docker": "ewatercycle/hype-grpc4bmi", "singularity": "ewatercycle-hype-grpc4bmi.sif"}, "msg": "Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on vagrant.localhost's Python /usr/bin/python3. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: cannot import name '__version__'"}

```

**Comment by SarahAlidoost** [comment]
For Walrun notebook FileNotFoundError: [Errno 2] No such file or directory: 'svn': 'svn'

**Comment by sverhoeven** [comment]
Successfully provisioned server, all checks pass

1. [x] Verify ewatercycle conda env is only kernel, after restart of notebook server
1. [x] Verify ewatercycle conda env is active in Jupyter terminal and after ssh login
1. [x] run https://github.com/eWaterCycle/notebooks/blob/master/bmi/Walrus.ipynb, used `ewatercycle/walrus-grpc4bmi:v0.2.0` Docker image and added `only_use_cftime_datetimes=False` to num2date()
1. [x] run geoviews example notebook (https://github.com/holoviz/hvplot/blob/master/examples/user_guide/Geographic_Data.ipynb), after running `bokeh.sampledata.download()`
1. [x] test code formatter extension
1. [x] run pymt example notebook (sample-notebooks/pymt/pymt_hydrotrend.ipynb)
1. [x] test [dask extension](https://github.com/dask/dask-examples/blob/master/xarray.ipynb)
1. [x] Test `esmvaltool --help`

**Comment by Peter9192** [comment]
Wow! Great job Stefan, still so much more for me to learn about this

**Pull request merged**
